# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist = True
skip_missing_interpreters = True
envlist = lint, format

[vars]
tests_path = {toxinidir}/tests/

[testenv]
allowlist_externals =
    /bin/bash
    uv
basepython = python3.12
set_env =
    PYTHONPATH = {toxinidir}
    PY_COLORS = 1

[testenv:lint]
description = Lint python code
deps = .[lint]
commands =
    uv run codespell {[vars]tests_path}
    uv run ruff check {[vars]tests_path}
    uv run ruff format --check --diff {[vars]tests_path}

[testenv:format]
description = Apply coding style standards to code
deps = .[format]
commands =
    uv run ruff check --fix {[vars]tests_path}
    uv run ruff format {[vars]tests_path}

[testenv:framework]
description = Test the UAT framework's fixtures against a deployment
deps = .[uats]
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}test_framework.py
